/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-04-04 12:15:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/gb_enh/jsp02/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SXTMovie/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1680423686739L));
    _jspx_dependants.put("jar:file:/C:/gb_enh/jsp02/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/SXTMovie/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" href='style.css'>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp\" crossorigin=\"anonymous\">\r\n");
      out.write("	");
 if(session.getAttribute("MovieList")==null){response.sendRedirect("./sxt/crawl.mo");}
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header id=\"header\"></header>\r\n");
      out.write("     <div class=\"container c_banner\">\r\n");
      out.write("            <div class=\"row main_banner\" >\r\n");
      out.write("         		<img src=\"https://caching2.lottecinema.co.kr/lotte_image/2023/JohnWick/JohnWick_1920774.jpg\" class=\"banner_img\" alt=\"...\">\r\n");
      out.write("                <div class=\"col banner_set\">\r\n");
      out.write("                    <div class=\"col\">\r\n");
      out.write("                        <h1 id=\"movie_name\" >존 윅 4</h1>\r\n");
      out.write("                        <p id=\"short_info\" >\r\n");
      out.write("                            북미 박스오피스 1위 <br>\r\n");
      out.write("                            전 세계를 열광 시킨 액션 블록버스터 ! <br>\r\n");
      out.write("                        </p>\r\n");
      out.write("                        <div id=\"banner_button_set\">\r\n");
      out.write("                            <div>\r\n");
      out.write("                                <a href=\"#\" class=\"btn btn-dark detail_b\"> 상세보기&nbsp;&nbsp;> </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <i class=\"bi bi-pause-circle pause\"> </i>\r\n");
      out.write("                            <i class=\"bi bi-volume-mute mute\"> </i>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container\" id=\"cardcontainer\">\r\n");
      out.write("                <div class=\"row r_moviechart\">\r\n");
      out.write("                    <div class=\"chart_text\">\r\n");
      out.write("                            <h1 id=\"movie_chart\" > 무비 차트 </h1>&nbsp;&nbsp;\r\n");
      out.write("                            <h1 id=\"movie_rank\" style=\"display:inline !important;\"> TOP 5 </h1>\r\n");
      out.write("                            <div style=\"display:inline !important;\">\r\n");
      out.write("                                <h5 id=\"more_chart\" >\r\n");
      out.write("                                    차트 더 보기\r\n");
      out.write("                                    <i href=\"#\" class=\"bi bi-plus-square-fill plus_icon\"></i>\r\n");
      out.write("                                </h5>\r\n");
      out.write("                            </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                <div class=\"row card_moviechart\">\r\n");
      out.write("                    <div class=\"col card_frameset\">\r\n");
      out.write("                        <div class=\"row cardset\">\r\n");
      out.write("                            <div class=\"card text-center card_posterFrame\">\r\n");
      out.write("                            	<div class=\"cardimg\">\r\n");
      out.write("                            		<strong>1</strong>\r\n");
      out.write("	                                <img src=\"https://img.cgv.co.kr/Movie/Thumbnail/Poster/000086/86909/86909_320.jpg\" class=\"card-img-top\" alt=\"1위\">\r\n");
      out.write("                            	</div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <h5 class=\"card-title\">존 윅 4 </h5>\r\n");
      out.write("                                    <h6 class=\"card-text\">\r\n");
      out.write("                                        예매율 00% |  골든 00%\r\n");
      out.write("                                    </h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary ticketing\">예매하기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col card_frameset\">\r\n");
      out.write("                        <div class=\"row cardset\">\r\n");
      out.write("                            <div class=\"card text-center card_posterFrame\">\r\n");
      out.write("                            	<div class=\"cardimg\">\r\n");
      out.write("                            		<strong>1</strong>\r\n");
      out.write("	                                <img src=\"https://img.cgv.co.kr/Movie/Thumbnail/Poster/000086/86909/86909_320.jpg\" class=\"card-img-top\" alt=\"1위\">\r\n");
      out.write("                            	</div>                            \r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <h5 class=\"card-title\">존 윅 4 </h5>\r\n");
      out.write("                                    <h6 class=\"card-text\">\r\n");
      out.write("                                        예매율 00% |  골든 00%\r\n");
      out.write("                                    </h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary ticketing\">예매하기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col card_frameset\">\r\n");
      out.write("                        <div class=\"row cardset\">\r\n");
      out.write("                            <div class=\"card text-center card_posterFrame\">\r\n");
      out.write("                            	<div class=\"cardimg\">\r\n");
      out.write("                            		<strong>1</strong>\r\n");
      out.write("	                                <img src=\"https://img.cgv.co.kr/Movie/Thumbnail/Poster/000086/86909/86909_320.jpg\" class=\"card-img-top\" alt=\"1위\">\r\n");
      out.write("                            	</div>\r\n");
      out.write("                                <div class=\"card-body\">\r\n");
      out.write("                                    <h5 class=\"card-title\">존 윅 4 </h5>\r\n");
      out.write("                                    <h6 class=\"card-text\">\r\n");
      out.write("                                        예매율 00% |  골든 00%\r\n");
      out.write("                                    </h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary ticketing\">예매하기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col card_frameset\">\r\n");
      out.write("                        <div class=\"row cardset\">\r\n");
      out.write("                            <div class=\"card text-center card_posterFrame\">\r\n");
      out.write("                            	<div class=\"cardimg\">\r\n");
      out.write("                            		<strong>1</strong>\r\n");
      out.write("	                                <img src=\"https://img.cgv.co.kr/Movie/Thumbnail/Poster/000086/86909/86909_320.jpg\" class=\"card-img-top\" alt=\"1위\">\r\n");
      out.write("                            	</div>                                <div class=\"card-body\">\r\n");
      out.write("                                    <h5 class=\"card-title\">존 윅 4 </h5>\r\n");
      out.write("                                    <h6 class=\"card-text\">\r\n");
      out.write("                                        예매율 00% |  골든 00%\r\n");
      out.write("                                    </h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary ticketing\">예매하기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col card_frameset\">\r\n");
      out.write("                        <div class=\"row cardset\">\r\n");
      out.write("                            <div class=\"card text-center card_posterFrame\">\r\n");
      out.write("                            	<div class=\"cardimg\">\r\n");
      out.write("                            		<strong>1</strong>\r\n");
      out.write("	                                <img src=\"https://img.cgv.co.kr/Movie/Thumbnail/Poster/000086/86909/86909_320.jpg\" class=\"card-img-top\" alt=\"1위\">\r\n");
      out.write("                            	</div>                                <div class=\"card-body\">\r\n");
      out.write("                                    <h5 class=\"card-title\">존 윅 4 </h5>\r\n");
      out.write("                                    <h6 class=\"card-text\">\r\n");
      out.write("                                        예매율 00% |  골든 00%\r\n");
      out.write("                                    </h6>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-primary ticketing\">예매하기</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    <footer id=\"footer\"></footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script src='function.js'></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
